name: Terraform Apply

on:
    push:
      branches: 
        - main
        - development
      paths: 
        - ecs-terraform/**
    pull_request:
      branches: 
        - main
        - development
      paths: 
        - ecs-terraform/**

jobs:
    terraform:
        name: "Apply terraform code changes"
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./ecs-terraform
        steps:
        - name: Checkout source code 
          uses: actions/checkout@v4

        - name: Set AWS Credentials
          run: |
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              echo "Using production credentials"
              echo "AWS_ACCESS_KEY_ID=${{ secrets.PROD_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
              
            elif [[ "${{ github.ref }}" == "refs/heads/development" ]]; then
              echo "Using development credentials"
              echo "AWS_ACCESS_KEY_ID=${{ secrets.DEV_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
              
            else
              echo "Unsupported branch: ${{ github.ref }}"
              exit 1
            fi

        - name: Install Terraform
          run: |
            TERRAFORM_VERSION=1.5.0  
            curl -fsSL https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -o terraform.zip
            sudo apt-get update && sudo apt-get install -y unzip
            unzip terraform.zip
            sudo mv terraform /usr/local/bin/
            terraform -version

        - name: Terraform Init
          id: init
          run: |
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              terraform init -backend-config "bucket=${{ secrets.BUCKET_TF_STATE_PROD }}"
            elif [[ "${{ github.ref }}" == "refs/heads/development" ]]; then
              terraform init -backend-config "bucket=${{ secrets.BUCKET_TF_STATE_DEV }}"
            else
              echo "Unsupported branch: ${{ github.ref }}"
              exit 1
            fi

        - name: Terraform Format
          id: fmt
          run: terraform fmt -check
          continue-on-error: true 

        - name: Terraform Validate
          id: validate
          run: terraform validate

        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color -input=false -out planfile
          continue-on-error: true 

        - name: Terraform Plan Status 
          if: steps.plan.outcome == 'failure'
          run: exit 1

        - name: Terraform Apply
          id: apply
          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
          run: terraform apply -auto-approve -input=false -parallelism=1 planfile