name: Terraform Apply

on:
    workflow_dispatch:
    push:
      branches: 
        - main
        - development
    
    pull_request:
      branches: 
        - main
        - development

jobs:
    terraform:
        name: "Apply terraform code changes"
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./terraform
        steps:
        - name: Checkout source code 
          uses: actions/checkout@v4

        - name: Set AWS Credentials
          if: github.ref == 'refs/heads/main' 
          env: 
              AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          run: | 
            echo "Configuring AWS credentials for main..."
            export AWS_ACCESS_KEY_ID=${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
            export AWS_REGION="us-east-1"

        - name: Install Terraform
          run: |
            TERRAFORM_VERSION=1.10.1
            curl -fsSL https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -o terraform.zip
            sudo apt-get update && sudo apt-get install -y unzip
            unzip terraform.zip
            sudo mv terraform /usr/local/bin/
            terraform -version

        - name: Terraform Init
          id: init
          if: github.ref == 'refs/heads/main' 
          run: |
            terraform init \
            -backend-config="bucket=${{ secrets.BUCKET_TF_STATE_PROD }}" \
            -backend-config="key="terraform.tfstate"" \
            -backend-config="region=us-east-1"

            
        - name: Terraform Format
          id: fmt
          run: terraform fmt -check
          continue-on-error: true 

        - name: Terraform Validate
          id: validate
          run: terraform validate

        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color -input=false -out planfile
          continue-on-error: true 

        - name: Terraform Plan Status 
          if: steps.plan.outcome == 'failure'
          run: exit 1

        - name: Terraform Apply
          id: apply
          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
          run: terraform apply -auto-approve -input=false -parallelism=1 planfile